# Generated by Django 4.2.11 on 2024-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ufc_fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rank', models.IntegerField(default=None, null=True)),
                ('is_champ', models.BooleanField(default=True)),
                ('next_opponent', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
