# Generated by Django 4.2.11 on 2024-04-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weight_division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ufc_fighter',
            name='weight_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='fighter.weight_division'),
        ),
    ]
